language: node_js

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test
  - node_js: "8"
    env: SCRIPT=test:e2e
  - node_js: "8"
    env: SCRIPT=test:protractor

before_install:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install
  - curl -fsSL get.docker.com -o get-docker.sh
  - chmod +x get-docker.sh
  - sudo ./get-docker.sh
  - sudo apt-get install sqlite3 -y

before_script:
  - sudo $(which node) ./tests/postinstall_ci.js
  - sudo usermod -aG docker abstruse
  - sudo /etc/init.d/docker start
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
