etcd:
  serveraddr: 127.0.0.1:2379
grpc:
  addr: 0.0.0.0:3330
  cert: /var/tmp/worker/cert.pem
  key: /var/tmp/worker/key.pem
scheduler:
  max: 2
log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-worker.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
