etcd:
  serveraddr: 127.0.0.1:2379
grpc:
  addr: 0.0.0.0:3340
  cert: /var/tmp/worker2/cert.pem
  key: /var/tmp/worker2/key.pem
scheduler:
  max: 4
log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-worker2.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
