etcd:
  serveraddr: 77.38.104.78:2379
grpc:
  addr: 0.0.0.0:8400
  cert: /var/tmp/worker3/cert.pem
  key: /var/tmp/worker3/key.pem
scheduler:
  max: 1
log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-worker3.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
