etcd:
  serveraddr: 127.0.0.1:2379
grpc:
  addr: 0.0.0.0:4400
  cert: /var/tmp/worker3/cert.pem
  key: /var/tmp/worker3/key.pem
maxcapacity: 1
log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-worker3.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
