tls:
  cert: /Users/jan/Dev/certs/_wildcard.jan.local.pem
  key: /Users/jan/Dev/certs/_wildcard.jan.local-key.pem

http:
  addr: 0.0.0.0:80
  tlsaddr: 0.0.0.0:443

websocket:
  addr: 127.0.0.1:7100

db:
  client: mysql
  hostname: localhost
  port: 3306
  user: abstruse
  password: abstruse
  name: abstruse_dev
  charset: utf8

etcd:
  name: abstruse
  host: 0.0.0.0
  clientport: 2379
  peerport: 2380
  datadir: /var/tmp/abstruse-server
  username: root
  password: abstruse

auth:
  jwtsecret: sfd919bUYxQ

log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-master.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
