tls:
  cert: /var/tmp/worker2/cert.pem
  key: /var/tmp/worker2/key.pem
etcd:
  addr: 127.0.0.1:2379
  username: root
  password: root
grpc:
  listenaddr: 0.0.0.0:3340
scheduler:
  maxconcurrency: 7
log:
  level: debug
  stdout: true
  filename: /tmp/abstruse-worker.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
