version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=abstruse
    networks:
      net:
        ipv4_address: 172.100.0.10
  abstruse_server:
    image: abstruse/abstruse-server
    container_name: abstruse-server
    restart: always
    volumes:
      - "./data/abstruse:/abstruse"
    ports:
      - 80:80
      - 443:443
      - 2379:2379
    environment:
      - ABSTRUSE_ADMIN_EMAIL=john@example.com
      - ABSTRUSE_ADMIN_NAME=John Doe
      - ABSTRUSE_ADMIN_PASSWORD=johndoe
      - ABSTRUSE_DB_HOSTNAME=172.100.0.10
      - ABSTRUSE_DB_NAME=abstruse
      - ABSTRUSE_DB_USERNAME=root
      - ABSTRUSE_DB_PASSWORD=abstruse
    networks:
      net:
        ipv4_address: 172.100.0.20
  abstruse_worker:
    image: abstruse/abstruse-worker
    container_name: abstruse-worker
    restart: always
    volumes:
      - "./data/abstruse-worker:/abstruse-worker"
      - "/tmp:/tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - ABSTRUSE_ETCD_ADDR=172.100.0.20:2379
      - ABSTRUSE_ETCD_USERNAME=abstruse
      - ABSTRUSE_ETCD_PASSWORD=abstruse
    networks:
      net:
        ipv4_address: 172.100.0.100

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
