version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: ractol-test-mysql
    restart: unless-stopped
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
